# Generated by Django 3.0.4 on 2020-04-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='id',
        ),
        migrations.AlterField(
            model_name='urls',
            name='shortcut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
