# Generated by Django 3.0.4 on 2020-04-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_auto_20200420_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='engine',
            field=models.CharField(max_length=2048, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='urls',
            name='shortcut',
            field=models.CharField(max_length=8),
        ),
    ]
